### ISSUE TITLE
Remove Persistent Volume Definitions

### ISSUE THREAD

**Issue by ThomasThelen** [DataONEorg/slinky#31]
At some point we're going to be using ceph storage which means deploying slinky locally will be very involved. There's also the architecture of the DataONE k8 cluster that enforces restrictions on who can create persistent volumes. Because of this, the persistent volume definitions should be moved out of this repository and into the DataONE k8 cluster repository. The development and production clusters will then have persistent volumes for slinky to make claims on.

**Comment by mbjones** [comment]
For the record, from the slinky perspective, using Ceph should be no more or less complicated than any other storage approach. In all cases, including Ceph, slinky simply needs to make a PVC on a predefined PV. That a particular PV is located on Ceph is of no concern to the application, although it does have improved persistence compared to, for example, a host based volume.

**Comment by ThomasThelen** [comment]
This has been fixed in PR #32 and successfully tested on development (non-ceph). The important thing is that the PV declarations are no longer in this project and refactoring have been done so that all pods use the same claim.
