### ISSUE TITLE
Change Default Account Passwords

### ISSUE THREAD

**Issue by ThomasThelen** [DataONEorg/slinky#35]
We should avoid using passwords for the default virtuoso accounts, for example `dba:dba` and `dav:dav`. We should be setting new passwords during deployment; see [this](http://docs.openlinksw.com/virtuoso/defpasschange/) documentation link for more information.

**Comment by amoeba** [comment]
Totally. I'll toss the docs for the official openlink image we're using in here: https://hub.docker.com/r/openlink/virtuoso-opensource-7. See the "Passwords". section.

> When a new database is created, the docker image will use the Environment settings DBA_PASSWORD and DAV_PASSWORD to set passwords for the dba and dav user accounts.

**Comment by ThomasThelen** [comment]
Completed in #42 ; deployments can manage the password in the environmental variable field
