### ISSUE TITLE
Create schema:Dataset nodes instead of geolink:Dataset

### ISSUE THREAD

**Issue by ThomasThelen** [DataONEorg/slinky#4]
Transform the geolink:Dataset object to, at a high level, conform to the schema,org model (schema:Dataset). For this task, ignore the representation of individuals. This representation should include the following properties, which can then be expanded on.

- name
- description
- url
- accessibility
- license
- identifier
- keywords
- connected EML document

Some of these aren’t super useful to know through the graph store. Ie how is DataONE going to leverage license information in the graph store? It probably won’t. The reason these are included is to comply with the SOSO recommendation that they be included. They’re also easy fields to include and “shouldn’t take much time”.

**Comment by mbjones** [comment]
See discussion of graph patern in #14

**Comment by amoeba** [comment]
Closing as this is done in https://github.com/DataONEorg/slinky/tree/feature_update_graph_pattern.
