### ISSUE TITLE
Configure networking via env vars

### ISSUE THREAD

**Issue by ThomasThelen** [DataONEorg/slinky#51]
We have a few deployment cases for slinky; at the moment we can configure these using an [environment](https://github.com/DataONEorg/slinky/blob/develop/d1lod/d1lod/settings.py#L10). In #43 I added a `--prod` flag to the cli which brings us further away from the pattern using environmental variables for this.

Instead, we should be able to configure the hosts in the kubernetes deployment file and the docker-compose definition.

This should involve 

- [x] Add environmental variables/config map to the pods using d1lod
- [x] Modify d1lod to use networking variables from the environment, with sensible backups (probably local store settings)

**Comment by amoeba** [comment]
This was done by @ThomasThelen and merged to develop in https://github.com/DataONEorg/slinky/pull/54.
