### ISSUE TITLE
Remove legacy code

### ISSUE THREAD

**Issue by ThomasThelen** [DataONEorg/slinky#55]
We have a folder of legacy code and a few unit tests that are tied down to it (test_metadata, test_graph, conftest). We probably want to decouple the legacy code from the tests and remove it from the code base

**Comment by amoeba** [comment]
Yes, please! I left it in while I was refactoring and it can safely go.

**Comment by amoeba** [comment]
Done in https://github.com/DataONEorg/slinky/commit/55c0a2169547583d1f1f4d6c1e05e8d123b8e945. Leaving open until merged.

**Comment by ThomasThelen** [comment]
Merged through #54 and #55. Closing
