### ISSUE TITLE
Support EML 2.0.1

### ISSUE THREAD

**Issue by ThomasThelen** [DataONEorg/slinky#63]
While testing Slinky on the PISCO datasets I saw a large number of failures because the associated metadata documents are using the `eml://ecoinformatics.org/eml-2.0.1` format, which we don't support.

It might be a good idea to add a new EML processor class to support this version so that we get these datasets in the graph.

**Comment by mbjones** [comment]
And EML 2.0.0 which is almost identical. It would be great to support all of the released versions of EML (2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.2.0).

**Comment by ThomasThelen** [comment]
I'm also noticing that a number of LTER datasets are failing since they're using 2.1.0. +1 for supporting all of the EML versions listed above so that we're not missing out on these datasets.

**Comment by ThomasThelen** [comment]
Support for EML 2.x.x was merged in #69
