### ISSUE TITLE
Reinstate rqdashboard

### ISSUE THREAD

**Issue by ThomasThelen** [DataONEorg/slinky#70]
Before putting the work in on the ELK stack, we can get high returns if we re-add the rqdashboard. This shouldn't be exposed to end users, and only accessible though proxying with kubectl

**Comment by amoeba** [comment]
rqdashboard is on develop now, both via docker compose and K8s YAML. https://github.com/DataONEorg/slinky/commit/cc77a5efc43d29aac50e76056f0abea74eef3438 and https://github.com/DataONEorg/slinky/commit/a6dc3b96561f71fa1e8e98a4956b5083cc42868a.
