### ISSUE TITLE
Create & Assign Early Milestones

### ISSUE THREAD

**Issue by ThomasThelen** [DataONEorg/slinky#8]
We should create a few milestones for work in the foreseeable future. From the 03/11/21 call we know that we need at the least, the graph up and running under K8 and that we want a schema,org representation of datasets and people. The work after (measured variable, files, geospatial, etc) is currently unordered.

1.0: Python 3 + Kubernetes Stack
2.0: Graph with schema:Dataset + schema:Person nodes

**Comment by amoeba** [comment]
I think these are created. Can this be closed?
